version: 2

sources:
  - name: raw_data
    description: Raw data loaded from Azure Blob Storage via external COPY INTO process
    schema: raw
    tables:
      - name: DISPATCH_PLAN

      - name: SOLUTION