version: 2

sources:
  - name: raw_data
    description: Raw data loaded from Azure Blob Storage via Snowpipe
    schema: raw
    tables:
      - name: SOLUTION
        description: DSP daily solution data (route assignments)
      
      - name: ROUTES
        description: Driver routes data from DSP Logistics portal